CREATE TABLE IF NOT EXISTS STOCKS (
    COMPANY VARCHAR(50),
    SYMBOL CHAR(5),
    INDX VARCHAR(3),
    VOLUME VARCHAR(20),
    PRICE VARCHAR(25),
    CHG VARCHAR(20),
    CHGPERCENT VARCHAR(10)
)  ENGINE=INNODB;